name: WakaTime Data Import

on:
  # Chỉ cho phép manual trigger để import data
  workflow_dispatch:
    inputs:
      days_to_import:
        description: 'Number of days to import (default 20)'
        required: false
        default: '20'
        type: string

jobs:
  import-wakatime:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Check git remote
      run: git remote -v

    - name: Import WakaTime data
      env:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      run: |
        echo "Importing ${{ github.event.inputs.days_to_import }} days of WakaTime data..."
        python wakatime_import.py
        
    - name: Commit and push
      env:
        PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        echo "Set git user"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
        echo "Set remote URL with PAT"
        git remote set-url origin https://x-access-token:${PAT}@github.com/haru2503/wakatime-log.git
    
        echo "Check remote"
        git remote -v
    
        echo "Stage changes"
        git add wakatime_logs/
        git add charts/
    
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Import ${{ github.event.inputs.days_to_import }} days of WakaTime data $(date -u)"
          git push origin HEAD:main
        fi

    - name: Create import report
      run: |
        echo "## WakaTime Import Report - $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "- **Workflow Run**: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Days Imported**: ${{ github.event.inputs.days_to_import }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Triggered by**: Manual import" >> $GITHUB_STEP_SUMMARY
        echo "- **Runner**: ubuntu-latest (GitHub's server)" >> $GITHUB_STEP_SUMMARY
        echo "- **Cannot be manipulated by user**" >> $GITHUB_STEP_SUMMARY 